nodes:
  - input.recorded:
      #   input_dir: "~/Datasets/Development/videos/two_people_crossing.mp4"
      input_dir: "~/code/pkd-custom-projects/fortests/video_sequences/two_people_crossing"
  - model.yolo:
      weights_parent_dir: "~/code/"
  - custom_nodes.dabble.tracking:
      tracking_type: "mosse"
  - draw.bbox
  - draw.tag
  - dabble.fps
  - output.screen
