nodes:
- input.recorded:
    input_dir: ~/code/pkd-bus-allocation/data/input/video_1/bus_boarding_alighting_frames
- model.yolo:
    model_type: v4
    detect_ids: [0, 5]
    yolo_score_threshold: 0.4
- custom_nodes.dabble.bbox_filter
- custom_nodes.dabble.object_tracker
- custom_nodes.dabble.bus_checker
- custom_nodes.dabble.create_annotation
- draw.bbox
- custom_nodes.draw.annotation:
    keys: ["label", "track_id", "bus_status"]
    location: [[0.1, 0.1], [0.5, 0.5], [0.8, 0.8]]
- custom_nodes.draw.zone:
    zones: [
        [
            [0.521, 0.278],
            [0.638, 0.278],
            [0.573, 1],
            [0.156, 1],
        ],
        [
            [0.638, 0.278],
            [0.703, 0.278],
            [0.833, 1],
            [0.573, 1],
        ],
    ]
# - output.screen
- custom_nodes.output.frame_writer:
    filepath: data/output/output.csv
    output_dir: data/output/bus_boarding_alighting_frames
