# Mandatory configs
input: ["none"] # replace values
output:
  [
    "img",
    "seq_dir",
    "frame_idx",
    "frame_rate",
    "frame_size",
    "reset_model",
    "pipeline_end",
  ]

# Optional configs depending on node
input_dir: null
